### ISSUE TITLE
How to set alias for Show-ChildItemColumns

### ISSUE THREAD

**Issue by duhd1993** [lpatalas/ShowColumns#7]
Hello, thanks for the project. I want to set alias for the command with some parameters.
Here is what I did
```powershell
function ls_alias { Show-ChildItemColumns -exclude .* $args}
Set-Alias -Name ls -Value ls_alias  -Option AllScope
```
the ``$args`` does not seem to work correctly. I managed to get the first parameters passed in. But I cannot get it fully working correctly. Sorry I'm not familiar with powershell. Could you help me with the alias?

**Comment by lpatalas** [comment]
Hello @lonelykid. To make this work you have to use `@args` instead of `$args`. So your example should look like:
```
function ls_alias { Show-ChildItemColumns -exclude .* @args }
Set-Alias -Name ls -Value ls_alias  -Option AllScope
```

The difference is that `$args` will concatenate all arguments and pass them as single value while `@args` will pass each argument separately. This is called splatting and you can read more about it here: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting.

Hope that helps.

**Comment by lonelykid** [comment]
Thank you for the info. It seems not working. I did what you suggested, and tried ``ls -Recurse -Depth 1``. Only the first args is passed and unlimited depth of subfolders are listed.

**Comment by lpatalas** [comment]
I was able to reproduce it on PowerShell 5.1. It seems that in older versions of PowerShell there is a bug in `Get-ChildItem` cmdlet. This cmdlet is used internally by `Show-ChildItemColumns` to list files so it is also affected. The bug was reported here https://github.com/PowerShell/PowerShell/issues/3726.

From what I see it was fixed in version 6.0 so if you're able to use PowerShell Core 6.0 or newer it should solve your problem. I tested on `7.1.1` and your alias works ok. If you're stuck with 5.1 then let me know and maybe we'll come up with some workaround. :)

**Comment by lonelykid** [comment]
Thank you so much. I upgraded to poweshell 7.2. It solved the issue. now tab auto-completion does not work with the alias. I guess that's how it is. It's still unbelievable that microsoft has not pushed the fix to default powershell after almost 4 years.

**Comment by lpatalas** [comment]
Glad to hear that it helped.

PowerShell 5.1 is in maintenance mode now so it only receives security patches. All the new development is happening in PowerShell 7.x. Unfortunately the new one is not completely backwards-compatible with 5.1 and most of the libraries were not ported yet so we are stuck in this unfortunate situation of having two slightly different PowerShells for backwards-compatibility reasons. As long as you're not forced to use 5.1 it's a good idea to always install latest version and use that.
